modLoader="javafml"

loaderVersion="[44,)"

license="MIT"

issueTrackerURL="https://marco/Horse armors/issues"

[[mods]]
   modId="horse_armors"
   version="${version}"
   displayName="Horse armors"
   logoFile="icon.png"
   authors="restonic4"

description='''

'''

[[dependencies.horse_armors]]
   modId="forge"
   mandatory=true
   versionRange="[44,)"
   ordering="NONE"
   side="BOTH"

[[dependencies.horse_armors]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.19.3]"
   ordering="NONE"
   side="BOTH"

[[dependencies.horse_armors]]
   modId="restapi"
   mandatory=true
   versionRange="[0.9-1.19.3-Forge]"
   ordering="NONE"
   side="BOTH"
